# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pipgdm"
client_id = "722e08dc2fa6b45db33b932000bdf83c"
application_url = "https://mode-competitive-revision-cards.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "pipgdm.myshopify.com"

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mode-competitive-revision-cards.trycloudflare.com/auth/callback",
  "https://mode-competitive-revision-cards.trycloudflare.com/auth/shopify/callback",
  "https://mode-competitive-revision-cards.trycloudflare.com/api/auth/callback"
]
embedded = true

[pos]
embedded = false
